# Generated by Django 5.0.6 on 2024-05-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='law',
            fields=[
                ('id_law', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ano', models.ImageField(upload_to='')),
                ('situacao', models.TextField()),
                ('arq', models.TextField()),
            ],
        ),
    ]
