# Generated by Django 5.0.6 on 2024-05-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_law_title_alter_law_arq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='arq',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
