# Generated by Django 5.0.6 on 2024-05-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_law_arq'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='texto',
            field=models.TextField(default=89),
            preserve_default=False,
        ),
    ]
